Repository jenkinsci/bmc-cfa-plugin, pull requests merged in 2021-12, with the labels that each got.

#10 Update README.md
  README.md
Labels: enhancement

#11 Fix release drafter config
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#13 Initial release
  README.md
Labels: enhancement

#14 Initial release
  README.md
Labels: enhancement, breaking

#15 Fixed POM for CD
  pom.xml
Labels: bug

#16 Fix the release number
  README.md
  pom.xml
Labels: bug

#17 Update README.md
  README.md
Labels: bug

#18 Update pom.xml
  pom.xml
Labels: bug

#19 Version format
  README.md
  pom.xml
  src/main/webapp/images/reprtdb2.JPG
  src/main/webapp/images/reprtims.JPG
Labels: bug

#21 Update README.md
  README.md
Labels: bug
